Repository FE-Study-Archive/wikiFEdia, pull requests merged in 2022-06, with the labels that each got.

#4 #3 Feat. place personal init post by rule
  RULES.md
  김지영/220624.md
  박승훈/220624.md
  박재경/220624.md
  박재현/220624.md
  이원우/220624.md
  이윤경/220624.md
  황상윤/220624.md
Labels: 🥔 Gamza, 🧩 Feat

#6 #5 Feat. automatical template of Issue and PR
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🥔 Gamza, 🧩 Feat

#8 #7 Style. addition of title template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🥔 Gamza, 🎨 Style

#10 #9 Docs. update README.md
  README.md
Labels: 🌱 Coco, 📄Docs

#11 #9 Docs. index category minor change
  README.md
Labels: 🥔 Gamza, 📄Docs

#13 #12 Post. deep syntax and use of sass
  박승훈/220701.md
Labels: 🥔 Gamza, 📑 Post
